### ISSUE TITLE
#ask

### ISSUE THREAD

**Issue by zakirkun** [MuhBayu/covid19bot-indonesia#26]
Cara installnya gimana ya? apa harus install redis yah

**Comment by bayungrh** [comment]
Iya, butuh redis untuk menyimpan datanya.

**Comment by zakirkun** [comment]
ada referensi tutorial nya gak bang pas deploy ke heroku?

**Comment by bayungrh** [comment]
Bisa connect dari GitHub ke Heroku
https://devcenter.heroku.com/articles/github-integration

Lalu setup Config Vars di settings Heroku, sesuaikan dengan yang ada di .env.example

**Comment by zakirkun** [comment]
kalau redis mas? dimana yah host redis free?

**Comment by bayungrh** [comment]
di Heroku juga ada Add-ons untuk redis nya juga mas, free.
